[versions]
jakartaXml = "4.0.4"
glassfish = "4.0.5"
guava = "33.4.5-jre"

[libraries]
jakartaXml = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jakartaXml" }
glashfish = { module = "org.glassfish.jaxb:jaxb-runtime", version.ref = "glassfish" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
