/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.example.persistence.xml.model.XCustomer;
import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;

class AppTest {
    @Test
    void main() {
        String localHome = "C:/Users/Santiago.Concha/Downloads/movies/movies/persistence/xml";
        Path path = Paths.get(String.format("%s/%s", localHome, XCustomer.HOME));

        try {
            Files.walk(path).forEach(System.out::println);
        } catch (IOException e) {
            throw new RuntimeException(e);
        }
    }
}
